name: Demo Pull Requests
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Job-1 / Step-1"
      - name: Step 2
        run: echo "Job-1 / Step-2"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "Job-2 / Step-1"
      - name: Step 2
        run: echo "Job-2 / Step-2"
